version: '3.9'

services:

  frontend:
    container_name: frontend
    build: ./front
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start

    # planfiApi:
    #   image: planfiapi:${TAG: latest}
    #   build:
    #     context: ../
    #     dockerfile: server/Dockerfile
    #   ports:
    #     - "9001:9001"
    #   restart: on-failure
    #   environment:
    #    - ASPNERCORE_ENVIRONMENT=development
    #   networks:
    #   - my-network
  #    networks:
  #     my-network:
  #          external: true
  